version: '2'

services:
  web:
    image: project:latest
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - /usr/src/app/web
    command: /usr/local/bin/gunicorn -w 2 -b 0.0.0.0:8000 app:app
    networks:
      - backend

networks:
  backend:
    driver: "bridge"